### ISSUE TITLE
[BUG] The defined minimum version of Sphinx (5.1.0) is wrong - Sphinx 7.3 seems to be the actual minimum

### ISSUE THREAD

**Issue by Jackenmen** [liran-funaro/sphinx-markdown-builder#48]
**Describe the bug**
I tried testing the builder with the version of Sphinx I already use in my project - Sphinx 7.1.2. This resulted in a build failure.

**To Reproduce**
Run the following commands:
```
mkdir markdown-builder-repro
cd markdown-builder-repro
python -m venv .venv
. .venv/bin/activate
pip install sphinx==7.1.2 sphinx-markdown-builder==0.6.9
sphinx-quickstart --quiet --project repro --author repro
make markdown
```

The last command will fail:
```
$ make markdown
Running Sphinx v7.1.2

Extension error:
Could not import extension sphinx_markdown_builder (exception: cannot import name 'ExtensionMetadata' from 'sphinx.util.typing' (/tmp/markdown-builder-repro/.venv/lib/python3.10/site-packages/sphinx/util/typing.py))
make: *** [Makefile:20: markdown] Error 2
```

**Expected behavior**
Considering [the Sphinx lower-bound that is currently defined in the project](https://github.com/liran-funaro/sphinx-markdown-builder/blob/9c3411310c59d92e75e64d2fe2a2f349a39660f4/pyproject.toml#L23), I assumed that the project would build.

**Environment (please complete the following information):**
```
❯ pip freeze                
alabaster==0.7.16
babel==2.18.0
certifi==2026.2.25
charset-normalizer==3.4.5
docutils==0.20.1
idna==3.11
imagesize==2.0.0
Jinja2==3.1.6
MarkupSafe==3.0.3
packaging==26.0
Pygments==2.19.2
requests==2.32.5
snowballstemmer==3.0.1
Sphinx==7.1.2
sphinx-markdown-builder==0.6.9
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
tabulate==0.10.0
urllib3==2.6.3
```

**Additional context**
The builder works fine on Sphinx 7.3, which is when the `ExtensionMetadata` type annotation was introduced to Sphinx. There are warnings with the `sphinx-quickstart` repro, but that's besides the point.

**Comment by liran-funaro** [comment]
@Jackenmen Thanks for the report.
The `ExtensionMetadata` import is unnecessary. I removed it. Now it I don't see issues:

I tested it in a docker image `docker run -it --rm python:3.13 bash`
```
git clone https://github.com/liran-funaro/sphinx-markdown-builder.git
pip install sphinx==5.1.0 standard-imghdr sphinx-markdown-builder/.
mkdir test
cd test
sphinx-quickstart --quiet --project repro --author repro
make markdown
```

Output:
```
Running Sphinx v5.1.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [markdown]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                                                                                   
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                                                                                    
build succeeded.
```

**Comment by Jackenmen** [comment]
Awesome, it works now! Would it be possible to publish this fix on PyPI as well?

**Comment by liran-funaro** [comment]
released: https://pypi.org/project/sphinx-markdown-builder/0.6.10/
